### ISSUE TITLE
Modular Entropy Multiplication?

### ISSUE THREAD

**Issue by BurtHarris** [alwynallan/redoubler#1]
This is very interesting, I was considering prototyping something similar using a CY8CKIT-059 I have sitting around unused.   I'm glad I found your project, thank you Peter.   

I'm interested why you use the term MEM to describe it.   It doesn't seem to involve modular arithmetic, have I missed something?

**Comment by alwynallan** [comment]
Hi Burt,

I have made this work on at CY8KIT-059, but there are some minor issues:
- Two of the pins that I used in REDOUBLER have capacitors connected
  between them and ground, so they wouldn't work as-is. For me it was easier
  to reassign to other GPIO pins, than to remove the capacitors. You'll see
  the change in the attached PNG file, and the updated firmware is also there.
- The REDOUBLER uses a 3.3V regulator to get clean power, but the
  CY8KIT-059 uses the 5V USB power directly. Noise on the power lines can
  cause the generator to temporarily lock up, producing hundreds of 1's or
  0's (I forget which) in a row. This lock-up can be made less likely by
  lowering the loop gain below 2.0, and that is the reason for the 9.53K
  resistors that you mentioned. On CY8KIT-059 I would go further to 9.1K or
  even 8.2K for those resistors.
- The LED supplied with CY8KIT-059 is on a different pin, referenced to
  ground, and much dimmer than the one I used. I made firmware changes to
  correct for these things.

The name MEM is a bit of a compromise. Bill Cox invented
https://github.com/waywardgeek/infnoise this method of generating random
bits independently form me (I was first, but I kept it secret to preserve
patent rights. He published it, and I have since disavowed any patent
interest.) Bill has an explanation of how this is like mod-2
multiplication, and that led to the name.

GMail won't accept the attachment, so the files you need are here:

http://apa.hopto.org/REDOUBLER_DIY.zip

A. Peter Allan · 450 Timber Lane · Devon PA 19333 · 610-687-1708 ·
610-547-4836 mobile

**Comment by BurtHarris** [comment]
Thank you Peter, that looks pretty easy, I'll give it a shot.

**Comment by BurtHarris** [comment]
Success.   I've assembled one, built the software, and flashed it.   Smoke test succeeded (no smoke), and I can see "audio" input coming from the device.   I've[ forked the project ](https://github.com/BurtHarris/redoubler-diy#redoubler-diy) to track your CY8KIT-059 code variant, and any changes I make.   Have a look at the photo.       

Thank you.
