### ISSUE TITLE
Broken link for OSH Park board source

### ISSUE THREAD

**Issue by BurtHarris** [alwynallan/redoubler#2]
Clicking the "OSH Park" link just below the board image in the Readme file takes me to a 404 error at https://oshpark.com/shared_projects/GZnEjhlQ

**Comment by alwynallan** [comment]
The design has had some iterations since I updated the GitHub. The latest
files are attached. You can drag-and-drop the .brd file to OSHPark to get
them made.

I had poor yield (~50%) producing these in my workshop. I think solder
bridges under the tiny chip caused most problems. I understand that is
normal with these packages, and that professional assemblers do much better
(98+%).

I was tempted to take it into production but the horror show of ONERNG
https://www.kickstarter.com/projects/moonbaseotago/onerng-an-open-source-entropy-generator/updates
scared me from it - he had everything from fake components to legionnaire's
disease. Luckily I'm not supporting myself with these interests; I'm an
investor.

A. Peter Allan · 450 Timber Lane · Devon PA 19333 · 610-687-1708 ·
610-547-4836 mobile
