### ISSUE TITLE
Integration with Linux

### ISSUE THREAD

**Issue by mhalano** [alwynallan/redoubler#6]
On a Debian system I can install the package 'rng-tools5' and use this tool to redirect the entropy from a device (like /dev/video0) to the random device (/dev/random). I was wondering what is the correct device under /dev/ for the microphone.

**Comment by alwynallan** [comment]
I don't know exactly how USB microphones work with the Linux /dev/ structure. I always used asound libraries to access it. The linux software provided works with Ubuntu and Raspian, which are both Debian based.

Currently I am working on a major re-write to the firmware, because Cypress no longer supports the USB-Audio codebase, and it won't compile with the latest version of PSoC Creator. The new firmware will connect as a USB CDC terminal, no driver needed, and use a udev rule to mount as /dev/REDOUBLER which can be accessed by rngd (rng-tools). It can also provides optional whitening, and 4x the bitrate, 4Mbps. It can produce a diagnostic page like [this](https://apa.hopto.org/redoubler.html). I'll have both the custom key, and a DIY version that uses Cypress CY8CKIT-059 for $10.

More soon.
